import type { CreativeBrief, BrandIdentityKit } from "@/types";

export const mockCreativeBrief: CreativeBrief = {
  visualDNA: {
    brand_color_mood: {
      descriptors: [
        "Warm, inviting emotional temperature",
        "Playful yet sophisticated",
        "Bright, optimistic personality",
        "Soft, approachable warmth",
        "Premium, elevated mood",
        "Joyful, celebratory energy",
        "Gentle, comforting presence",
        "Vibrant, life-affirming",
        "Nurturing, caring atmosphere",
        "Elegant, refined tone",
        "Cheerful, uplifting spirit",
        "Luxurious, indulgent feel",
        "Fresh, invigorating sensation",
        "Harmonious, balanced energy",
        "Inspiring, motivational quality",
      ],
      avoid: ["Cold", "Harsh", "Aggressive", "Somber", "Dull"],
    },
    typography_voice: {
      descriptors: [
        "Playful, rounded letterforms",
        "Friendly, approachable structure",
        "Modern, clean geometric base",
        "Elegant, refined serif accents",
        "Bold, confident weight",
        "Delicate, refined details",
        "Spacious, breathing letter-spacing",
        "Organic, flowing curves",
        "Premium, crafted appearance",
        "Readable, accessible forms",
        "Expressive, characterful shapes",
        "Balanced, harmonious proportions",
        "Sophisticated, timeless design",
        "Warm, humanistic quality",
        "Distinctive, memorable personality",
      ],
      avoid: ["Rigid", "Cold", "Corporate", "Stiff", "Mechanical"],
    },
    logo_geometry_essence: {
      descriptors: [
        "Rounded, soft silhouettes",
        "Organic, flowing line-weight",
        "Playful, asymmetric balance",
        "Elegant, refined tension",
        "Bold, confident presence",
        "Delicate, intricate details",
        "Modern, minimal structure",
        "Warm, approachable form",
        "Premium, crafted quality",
        "Distinctive, memorable shape",
        "Fluid, dynamic movement",
        "Sophisticated, timeless design",
        "Friendly, welcoming presence",
        "Bold, impactful scale",
        "Refined, elegant proportions",
      ],
      avoid: ["Sharp", "Geometric", "Cold", "Corporate", "Stiff"],
    },
    photography_cinematic_world: {
      backgrounds: [
        "Soft, diffused natural light",
        "Warm, inviting environments",
        "Clean, minimal settings",
        "Textured, organic surfaces",
        "Bright, airy spaces",
      ],
      models: [
        "Diverse, authentic representation",
        "Genuine, natural expressions",
        "Warm, approachable poses",
        "Celebratory, joyful moments",
        "Confident, comfortable presence",
      ],
      products: [
        "Hero-focused compositions",
        "Natural, unforced arrangements",
        "Textured, tactile presentation",
        "Warm, inviting styling",
        "Premium, elevated positioning",
      ],
      lighting: [
        "Soft, diffused natural light",
        "Warm, golden hour quality",
        "Gentle, flattering illumination",
        "Bright, optimistic atmosphere",
        "Luxurious, premium ambiance",
      ],
      avoid: ["Harsh", "Cold", "Over-styled", "Artificial", "Clinical"],
    },
    illustration_style_medium: {
      descriptors: [
        "Hand-drawn, organic quality",
        "Watercolor, soft textures",
        "Playful, expressive style",
        "Elegant, refined technique",
        "Warm, inviting colors",
        "Premium, crafted appearance",
        "Modern, contemporary approach",
        "Nostalgic, timeless feel",
        "Bold, confident strokes",
        "Delicate, intricate details",
        "Textured, tactile materials",
        "Vibrant, life-affirming palette",
        "Sophisticated, nuanced style",
        "Friendly, approachable forms",
        "Distinctive, memorable character",
      ],
      avoid: ["Flat", "Cold", "Corporate", "Mechanical", "Generic"],
    },
  },
};

export const mockBrandKit: BrandIdentityKit = {
  logoUrl: null,
  assets: [],
  isLoadingLogo: false,
  isLoadingAssets: false,
};
